export let arincLayout = {
  // xx: {
  //   title: "",
  //   re: ".{4}xx{128}",
  //   contNr: [
  //     {
  //       title: "4.1.5.1 Holding Pattern Primary",
  //       layout: [
  //         { name: "Record Type (1) ", reference: "5.2 ", textDirection: "" },
  //       ],
  //     },
  //   ],
  // },

  // NDB NAVAID Record (DB or PN)
  dbpn: {
    title: "NDB NAVAID Record (DB or PN)",
    re: ".{4}(db|pn).{126}",
    contNr: [
      {
        title: "4.1.3.1 NDB NAVAID Primary",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "7 thru 10 ", name: "Airport ICAO Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "14 thru 17 ", name: "NDB Identifier (4) ", reference: "5.33 ", },
          { column: "18 thru 19 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 thru 27 ", name: "NDB Frequency (5) ", reference: "5.34 ", },
          { column: "28 thru 32 ", name: "NDB Class (5) ", reference: "5.35 ", },
          { column: "33 thru 41 ", name: "NDB Latitude (9) ", reference: "5.36 ", },
          { column: "42 thru 51 ", name: "NDB Longitude (10) ", reference: "5.37 ", },
          { column: "52 thru 74 ", name: "Blank (Spacing) (23) ", reference: " ", },
          { column: "75 thru 79 ", name: "Magnetic Variation (5) ", reference: "5.39 ", },
          { column: "80 thru 85 ", name: "Blank (Spacing) (6) ", reference: " ", },
          { column: "86 thru 90 ", name: "Reserved (Expansion) (5) ", reference: " ", },
          { column: "91 thru 93 ", name: "Datum Code (3) ", reference: "5.197 ", },
          { column: "94 thru 123 ", name: "NDB Name (30) ", reference: "5.71 ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Data (4) ", reference: "5.32 ", },
        ],
      },
      {
        title: "4.1.3.2 NDB NAVAID Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "7 thru 10 ", name: "Airport ICAO Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "14 thru 17 ", name: "NDB Identifier (4) ", reference: "5.33 ", },
          { column: "18 thru 19 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24 thru 92 ", name: "Notes (69) ", reference: "5.61 ", },
          { column: "93 thru 123 ", name: "Reserved (Expansion) (31) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Data (4) ", reference: "5.32 ", },
        ],
      },
      {
        title: "4.1.3.3 NDB NAVAID Simulation Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "7 thru 10 ", name: "Airport ICAO Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "14 thru 17 ", name: "NDB Identifier (4) ", reference: "5.33 ", },
          { column: "18 thru 19 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24 thru 27 ", name: "Blank (Spacing) (4) ", reference: " ", },
          { column: "28 thru 32 ", name: "Facility Characteristics (5) ", reference: "5.93 ", },
          { column: "33 thru 79 ", name: "Reserved (Spacing) (47) ", reference: " ", },
          { column: "80 thru 84 ", name: "Facility Elevation (5) ", reference: "5.92 ", },
          { column: "85 thru 123 ", name: "Reserved (Expansion) (39) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Data (4) ", reference: "5.32 ", },
        ],
      },
      {
        title: "4.1.3.4 NDB NAVAID Flight Planning Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "7 thru 10 ", name: "Airport ICAO Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "14 thru 17 ", name: "NDB Identifier (4) ", reference: "5.33 ", },
          { column: "18 thru 19 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24 thru 27 ", name: "FIR Identifier (4) ", reference: "5.116 ", },
          { column: "28 thru 31 ", name: "UIR Identifier (4) ", reference: "5.116 ", },
          { column: "32 ", name: "Start/End Indicator (1) ", reference: "5.152 ", },
          { column: "33 thru 43 ", name: "Blank (Spacing) (11) ", reference: " ", },
          { column: "44 thru 123 ", name: "Reserved (Expansion) (80) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
    ],
  },

  // Waypoint (EA) or (PC)
  eapc: {
    title: "Waypoint (EA) or (PC) ",
    re: ".{4}(ea|pc).{126}",
    contNr: [
      {
        title: "4.1.4.1 Waypoint Primary",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5", },
          { column: "7 thru 10 ", name: "Region Code (4) ", reference: "5.41 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2)  ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection (1) ", reference: "5.5 ", },
          { column: "14 thru 18 ", name: "Waypoint Identifier (5)  ", reference: "5.13 ", },
          { column: "19 ", name: "Blank (Spacing) (1)  ", reference: " ", },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "22 ", name: "Continuation Record No. (1)  ", reference: "5.16 ", },
          { column: "23 thru 26 ", name: "Blank (Spacing) (4)  ", reference: " ", },
          { column: "27 thru 29 ", name: "Waypoint Type (3) ", reference: "5.42 ", },
          { column: "30 thru 31 ", name: "Waypoint Usage (2) ", reference: "5.82 ", },
          { column: "32 ", name: "Blank (Spacing) (1)  ", reference: " ", },
          { column: "33 thru 41 ", name: "Waypoint Latitude (9) ", reference: "5.36 ", },
          { column: "42 thru 51 ", name: "Waypoint Longitude (10) ", reference: "5.37 ", },
          { column: "52 thru 74 ", name: "Blank (Spacing) (23) ", reference: " ", },
          { column: "75 thru 79 ", name: "Dynamic Magnetic Variation (5) ", reference: "5.39 ", },
          { column: "80 thru 84 ", name: "Reserved (Expansion) (5) ", reference: " ", },
          { column: "85 thru 87 ", name: "Datum Code (3) ", reference: "5.197 ", },
          { column: "88 thru 95 ", name: "Reserved (Expansion) (8) ", reference: " ", },
          { column: "96 thru 98 ", name: "Name Format Indicator (3) ", reference: "5.196 ", },
          { column: "99 thru 123 ", name: "Waypoint Name/Description (25) ", reference: "5.43 ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
      {
        title: "4.1.4.2 Waypoint Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5", },
          { column: "7 thru 10 ", name: "Region Code (4) ", reference: "5.41 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2)  ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection (1) ", reference: "5.5 ", },
          { column: "14 thru 18 ", name: "Waypoint Identifier (5)  ", reference: "5.13 ", },
          { column: "19 ", name: "Blank (Spacing) (1)  ", reference: " ", },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24 thru 92 ", name: "Notes (69) ", reference: "5.61 ", },
          { column: "93 thru 123 ", name: "Reserved (Expansion) (31) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Data (4) ", reference: "5.32 ", },
        ],
      }, {
        title: "4.1.4.3 Waypoint Flight Planning Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5", },
          { column: "7 thru 10 ", name: "Region Code (4) ", reference: "5.41 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2)  ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection (1) ", reference: "5.5 ", },
          { column: "14 thru 18 ", name: "Waypoint Identifier (5)  ", reference: "5.13 ", },
          { column: "19 ", name: "Blank (Spacing) (1)  ", reference: " ", },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24 thru 27 ", name: "FIR Identifier (4) ", reference: "5.116 ", },
          { column: "28 thru 31 ", name: "UIR Identifier (4) ", reference: "5.116 ", },
          { column: "32 ", name: "Start/End Indicator (1) ", reference: "5.152 ", },
          { column: "33 thru 43 ", name: "Blank (Spacing) (11) ", reference: " ", },
          { column: "44 thru 123 ", name: "Reserved (Expansion) (80) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5)  ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4)  ", reference: "5.32 ", },
        ],
      },
    ],
  },

  // Holding Pattern (EP)
  ep: {
    title: "Holding Pattern (EP)",
    re: ".{4}ep.{126}",
    contNr: [
      {
        title: "4.1.5.1 Holding Pattern Primary",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "7 thru 10 ", name: "Region Code (4) ", reference: "5.41", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14", },
          { column: "13 thru 27 ", name: "Blank (Spacing) (15) ", reference: " ", },
          { column: "28 thru 29 ", name: "Duplicate Identifier (2) ", reference: "5.114 ", },
          { column: "30 thru 34 ", name: "Fix Identifier (5) ", reference: "5.13 ", },
          { column: "35 thru 36 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "37 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "38 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "39 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "40 thru 43 ", name: "Inbound Holding Course (4) ", reference: "5.62 ", },
          { column: "44 ", name: "Turn Direction (1) ", reference: "5.63 ", },
          { column: "45 thru 47 ", name: "Leg Length (3) ", reference: "5.64 ", },
          { column: "48 thru 49 ", name: "Leg Time (2) ", reference: "5.65 ", },
          { column: "50 thru 54 ", name: "Minimum Altitude (5) ", reference: "5.30 ", },
          { column: "55 thru 59 ", name: "Maximum Altitude (5) ", reference: "5.127 ", },
          { column: "60 thru 62 ", name: "Holding Speed (3) ", reference: "5.175 ", },
          { column: "63 thru 65 ", name: "RNP (3) ", reference: "5.211 ", },
          { column: "66 thru 71 ", name: "Arc Radius (6) ", reference: "5.204 ", },
          { column: "72 thru 74 ", name: "Vertical Scale Factor (3) ", reference: "5.293 ", },
          { column: "75 thru 77 ", name: "RVSM Minimum Level (3) ", reference: "5.294 ", },
          { column: "78 thru 80 ", name: "RVSM Maximum Level (3) ", reference: "5.295 ", },
          { column: "81 ", name: "Leg Inbound/Outbound Indicator (1) ", reference: "5.298 ", },
          { column: "82 thru 98 ", name: "Reserved (Expansion) (17) ", reference: " ", },
          { column: "99 thru 123 ", name: "Name (25) ", reference: "5.60 ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
      {
        title: "4.1.5.2 Holding Pattern Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "7 thru 10 ", name: "Region Code (4) ", reference: "5.41", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14", },
          { column: "13 thru 27 ", name: "Blank (Spacing) (15) ", reference: " ", },
          { column: "28 thru 29 ", name: "Duplicate Identifier (2) ", reference: "5.114 ", },
          { column: "30 thru 34 ", name: "Fix Identifier (5) ", reference: "5.13 ", },
          { column: "35 thru 36 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "37 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "38 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "39 ", name: "Continuation Record No. (1)  ", reference: "5.16 ", },
          { column: "40 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "41 thru 109 ", name: "Notes (69) ", reference: "5.61 ", },
          { column: "110 thru 123 ", name: "Reserved (Expansion) (14) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
    ],
  },

  // VHF NAVAID (D)
  d: {
    title: "VHF NAVAID (D)",
    re: ".{4}d..{126}",
    contNr: [
      {
        title: "4.1.2.1 VHF NAVAID Primary",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "7 thru 10 ", name: "Airport ICAO Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "14 thru 17 ", name: "VOR Identifier (4) ", reference: "5.33 ", },
          { column: "18 thru 19 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 thru 27 ", name: "VOR Frequency (5) ", reference: "5.34 ", },
          { column: "28 thru 32 ", name: "NAVAID Class (5) ", reference: "5.35 ", },
          { column: "33 thru 41 ", name: "VOR Latitude (9) ", reference: "5.36 ", },
          { column: "42 thru 51 ", name: "VOR Longitude (10) ", reference: "5.37 ", },
          { column: "52 thru 55 ", name: "DME Ident (4) ", reference: "5.38 ", },
          { column: "56 thru 64 ", name: "DME Latitude (9) ", reference: "5.36 ", },
          { column: "65 thru 74 ", name: "DME Longitude (10) ", reference: "5.37 ", },
          { column: "75 thru 79 ", name: "Station Declination (5) ", reference: "5.66 ", },
          { column: "80 thru 84 ", name: "DME Elevation (5) ", reference: "5.40 ", },
          { column: "85 ", name: "Figure of Merit (1) ", reference: "5.149 ", },
          { column: "86 thru 87 ", name: "ILS/DME Bias (2) ", reference: "5.90 ", },
          { column: "88 thru 90 ", name: "Frequency Protection (3) ", reference: "5.150 ", },
          { column: "91 thru 93 ", name: "Datum Code (3) ", reference: "5.197 ", },
          { column: "94 thru 118 ", name: "VOR Name (25) ", reference: "5.71 ", },
          { column: "119 thru 121 ", name: "Blank (Spacing) (3) ", reference: " ", },
          { column: "122 ", name: "Route Inappropriate DME (1) ", reference: "5.297 ", },
          { column: "123 ", name: "DME Operational Service Volume (1) ", reference: "5.277 ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },

        ],
      },
      {
        title: "4.1.2.2 VHF NAVAID Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "7 thru 10 ", name: "Airport ICAO Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "14 thru 17 ", name: "VOR Identifier (4) ", reference: "5.33 ", },
          { column: "18 thru 19 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24 thru 92 ", name: "Notes (69) ", reference: "5.61 ", },
          { column: "93 thru 123 ", name: "Reserved (Expansion) (31) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },

        ],
      },
      {
        title: "4.1.2.3 VHF NAVAID Simulation Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "7 thru 10 ", name: "Airport ICAO Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "14 thru 17 ", name: "VOR Identifier (4) ", reference: "5.33 ", },
          { column: "18 thru 19 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24 thru 27 ", name: "Blank (Spacing) (4) ", reference: " ", },
          { column: "28 thru 32 ", name: "Facility Characteristics (5) ", reference: "5.93 ", },
          { column: "33 thru 74 ", name: "Reserved (Spacing) (42) ", reference: " ", },
          { column: "75 thru 79 ", name: "Magnetic Variation (5) ", reference: "5.39 ", },
          { column: "80 thru 84 ", name: "Facility Elevation (5) ", reference: "5.92 ", },
          { column: "85 thru 123 ", name: "Reserved (Expansion) (39) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
      {
        title: "4.1.2.4 VHF NAVAID Flight Planning Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "7 thru 10 ", name: "Airport ICAO Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "14 thru 17 ", name: "VOR Identifier (4) ", reference: "5.33 ", },
          { column: "18 thru 19 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24 thru 27 ", name: "FIR Identifier (4) ", reference: "5.116 ", },
          { column: "28 thru 31 ", name: "UIR Identifier (4) ", reference: "5.116 ", },
          { column: "32 ", name: "Start/End Indicator (1) ", reference: "5.152 ", },
          { column: "33 thru 43 ", name: "Blank (Spacing) (11) ", reference: " ", },
          { column: "44 thru 123 ", name: "Reserved (Expansion) (80) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
      {
        title: "4.1.2.6 VHF NAVAID Limitation Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "7 thru 10 ", name: "Airport ICAO Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "14 thru 17 ", name: "VOR Identifier (4) ", reference: "5.33 ", },
          { column: "18 thru 19 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24 ", name: "Navaid Limitation Code (1) ", reference: "5.205 ", },
          { column: "25 ", name: "Component Affected Indicator (1) ", reference: "5.206 ", },
          { column: "26 thru 27 ", name: "Sequence Number (2) ", reference: "5.12 ", },
          { column: "28 thru 29 ", name: "Sector From/Sector To (2) ", reference: "5.207 ", },
          { column: "30 ", name: "Distance Description (1) ", reference: "5.187 ", },
          { column: "31 thru 36 ", name: "Distance Limitation (6) ", reference: "5.208 ", },
          { column: "37 ", name: "Altitude Description (1) ", reference: "5.29 ", },
          { column: "38 thru 43 ", name: "Altitude Limitation (6) ", reference: "5.209 ", },
          { column: "44 thru 45 ", name: "Sector From/Sector To (2) ", reference: "5.207 ", },
          { column: "46 ", name: "Distance Description (1) ", reference: "5.187 ", },
          { column: "47 thru 52 ", name: "Distance Limitation (6) ", reference: "5.208 ", },
          { column: "53 ", name: "Altitude Description (1) ", reference: "5.29 ", },
          { column: "54 thru 59 ", name: "Altitude Limitation (6) ", reference: "5.209 ", },
          { column: "60 thru 61 ", name: "Sector From/Sector To (2) ", reference: "5.207 ", },
          { column: "62 ", name: "Distance Description (1) ", reference: "5.187 ", },
          { column: "63 thru 68 ", name: "Distance Limitation (6) ", reference: "5.208 ", },
          { column: "69 ", name: "Altitude Description (1) ", reference: "5.29 ", },
          { column: "70 thru 75 ", name: "Altitude Limitation (6) ", reference: "5.209 ", },
          { column: "76 thru 77 ", name: "Sector From/Sector To (2) ", reference: "5.207 ", },
          { column: "78 ", name: "Distance Description (1) ", reference: "5.187 ", },
          { column: "79 thru 84 ", name: "Distance Limitation (6) ", reference: "5.208 ", },
          { column: "85 ", name: "Altitude Description (1) ", reference: "5.29 ", },
          { column: "86 thru 91 ", name: "Altitude Limitation (6) ", reference: "5.209 ", },
          { column: "92 thru 93 ", name: "Sector From/Sector To (2) ", reference: "5.207 ", },
          { column: "94 ", name: "Distance Description (1) ", reference: "5.187 ", },
          { column: "95 thru 100 ", name: "Distance Limitation (6) ", reference: "5.208 ", },
          { column: "101 ", name: "Altitude Description (1) ", reference: "5.29 ", },
          { column: "102 thru 107 ", name: "Altitude Limitation (6) ", reference: "5.209 ", },
          { column: "108 ", name: "Sequence End Indicator (1) ", reference: "5.210 ", },
          { column: "109 thru 123 ", name: "Blank (Spacing) (15) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
    ],
  },

  // 4.1.6 Enroute Airways Records (ER)

  // 4.1.7 Airport Records (PA)

  // 4.1.8 Airport Gate Records (PB)

  // 4.1.9 Airport SID/STAR/Approach (PD, PE and PF)

  // 4.1.10 Runway Records (PG)

  // 4.1.11 Airport and Heliport Localizer and Glide Slope Records (PI)

  // 4.1.12 Company Route Records (R)

  // 4.1.13 Airport and Heliport Localizer Marker Records (PM)

  // 4.1.14 Airport Communications Records (PV)
  pv: {
    title: "Airport Communications (PV)",
    re: ".{4}p.{7}v.{119}",
    contNr: [
      {
        title: "4.1.14.1 Airport Communications Primary Records",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "7 thru 10 ", name: "Airport Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "14 thru 15 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "16 thru 19 ", name: "Communication Class (4) ", reference: "5.283 ", },
          { column: "20 thru 21 ", name: "Sequence Number  (2) ", reference: "5.12 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 thru 25 ", name: "Communication Types (3) ", reference: "5.101 ", },
          { column: "26 thru 32 ", name: "Transmit Frequency (7) ", reference: "5.103 ", },
          { column: "33 thru 39 ", name: "Receive Frequency (7) ", reference: "5.103 ", },
          { column: "40 ", name: "Frequency Units (1) ", reference: "5.104 ", },
          { column: "41 ", name: "Radar Units (1) ", reference: "5.102 ", },
          { column: "42 ", name: "H24 Indicator (1) ", reference: "5.181 ", },
          { column: "43 thru 67 ", name: "Call Signs (25) ", reference: "5.105 ", },
          { column: "68 ", name: "Multi-Sector Indicator (1) ", reference: "5.286 ", },
          { column: "69 thru 74 ", name: "Sectorization (6) ", reference: "5.183 ", },
          { column: "75 thru 78 ", name: "Sector Facility (4) ", reference: "5.185 ", },
          { column: "79 thru 80 ", name: "ICAO (2) ", reference: "5.14 ", },
          { column: "81 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "82 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "83 ", name: "Altitude Description Code (1) ", reference: "5.29 ", },
          { column: "84 thru 86 ", name: "Communication Altitude 1 (3) ", reference: "5.184 ", },
          { column: "87 thru 89 ", name: "Communication Altitude 2 (3) ", reference: "5.184 ", },
          { column: "90 ", name: "Distance Description Code (1) ", reference: "5.187 ", },
          { column: "91 thru 92 ", name: "Communication Distance (2) ", reference: "5.188 ", },
          { column: "93 thru 101 ", name: "Transmitter Latitude (9) ", reference: "5.36 ", },
          { column: "102 thru 111 ", name: "Transmitter Longitude (10) ", reference: "5.37 ", },
          { column: "112 thru 114 ", name: "Service Indicator (3) ", reference: "5.106 ", },
          { column: "115 ", name: "Modulation (1) ", reference: "5.198 ", },
          { column: "116 ", name: "Signal Emission (1) ", reference: "5.199 ", },
          { column: "117 thru 123 ", name: "Blank (Spacing) (7) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
      {
        title: "4.1.14.2 Airport Communications Continuation Records",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "7 thru 10 ", name: "Airport Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "14 thru 15 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "16 thru 19 ", name: "Communication Class (4) ", reference: "5.283 ", },
          { column: "20 thru 21 ", name: "Sequence Number  (2) ", reference: "5.12 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24 thru 27 ", name: "Remote Facility (4) ", reference: "5.200 ", },
          { column: "28 thru 29 ", name: "ICAO (2) ", reference: "5.14 ", },
          { column: "30 ", name: "Section (1) ", reference: "5.4 ", },
          { column: "31 ", name: "Subsection (1) ", reference: "5.5 ", },
          { column: "32 thru 36 ", name: "Transmitter Site Mag Var (5) ", reference: "5.39 ", },
          { column: "37 thru 41 ", name: "Transmitter Site Elevation (5) ", reference: "5.92 ", },
          { column: "42 thru 47 ", name: "Additional Sectorization 1 (6) ", reference: "5.183 ", },
          { column: "48 ", name: "Additional Sectorization 1 Altitude Description (1) ", reference: "5.29 ", },
          { column: "49 thru 51 ", name: "Additional Sectorization 1 Altitude 1 (3) ", reference: "5.184 ", },
          { column: "52 thru 53 ", name: "Additional Sectorization 1 Altitude 2 (3) ", reference: "5.184 ", },
          { column: "54 thru 59 ", name: "Additional Sectorization 2 (6) ", reference: "5.183 ", },
          { column: "60 ", name: "Additional Sectorization 2 Altitude Description (1) ", reference: "5.29 ", },
          { column: "61 thru 63 ", name: "Additional Sectorization 2 Altitude 1 (3) ", reference: "5.184 ", },
          { column: "64 thru 66 ", name: "Additional Sectorization 2 Altitude 2 (3) ", reference: "5.184 ", },
          { column: "67 ", name: "Time Code (1) ", reference: "5.131 ", },
          { column: "68 ", name: "NOTAM (1) ", reference: "5.132 ", },
          { column: "69 ", name: "Time Indicator (1) ", reference: "5.138 ", },
          { column: "70 thru 79 ", name: "Time of Operation (10) ", reference: "5.195 ", },
          { column: "80 thru 89 ", name: "Time of Operation (10) ", reference: "5.195 ", },
          { column: "90 thru 99 ", name: "Time of Operation (10) ", reference: "5.195 ", },
          { column: "100 thru 109 ", name: "Time of Operation (10) ", reference: "5.195 ", },
          { column: "110 thru 119 ", name: "Time of Operation (10) ", reference: "5.195 ", },
          { column: "120 thru 123 ", name: "Blank (Spacing) (3) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },

        ],
      },
      {
        title: "4.1.14.3 Airport Communications Continuation Records",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "7 thru 10 ", name: "Airport Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "14 thru 15 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "16 thru 19 ", name: "Communication Class (4) ", reference: "5.283 ", },
          { column: "20 thru 21 ", name: "Sequence Number  (2) ", reference: "5.12 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24thru 83 ", name: "Sectorization Narrative (60) ", reference: "5.186 ", },
          { column: "84 thru 123  ", name: "Reserved (Spacing) (40) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
      {
        title: "4.1.14.4 Airport Communications Continuation Records",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "7 thru 10 ", name: "Airport Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "14 thru 15 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "16 thru 19 ", name: "Communication Class (4) ", reference: "5.283 ", },
          { column: "20 thru 21 ", name: "Sequence Number  (2) ", reference: "5.12 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24 thru 69 ", name: "Blank (Spacing) (46) ", reference: " ", },
          { column: "70 thru 79 ", name: "Time of Operation (10) ", reference: "5.195 ", },
          { column: "80 thru 89 ", name: "Time of Operation (10) ", reference: "5.195 ", },
          { column: "90 thru 99 ", name: "Time of Operation (10) ", reference: "5.195 ", },
          { column: "100 thru 109 ", name: "Time of Operation (10) ", reference: "5.195 ", },
          { column: "110 thru 119 ", name: "Time of Operation (10) ", reference: "5.195 ", },
          { column: "120 thru 123 ", name: "Blank (Spacing) (4) ", reference: " ", },
          { column: "124 thru 128  ", name: "File Record numbers (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },

        ],
      },
      {
        title: "4.1.14.5 Airport Communications Continuation Records",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "7 thru 10 ", name: "Airport Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "14 thru 15 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "16 thru 19 ", name: "Communication Class (4) ", reference: "5.283 ", },
          { column: "20 thru 21 ", name: "Sequence Number  (2) ", reference: "5.12 ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24 thru 123 ", name: "Time Narrative (100) ", reference: "5.285 ", },
          { column: "124 thru 128  ", name: "File Record numbers (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },

        ],
      },
    ],
  },

  // 4.1.15 Airways Marker Records (EM)

  // 4.1.16 Cruising Tables Records (TC)

  // 4.1.17 FIR/UIR Records (UF)

  // 4.1.18 Restrictive Airspace Records (UR)

  // 4.1.19 Grid MORA Records (AS)

  // 4.1.20 Airport MSA (Minimum Sector Altitude) Records (PS)

  // 4.1.21 Enroute Airways Restriction Records (EU)

  // 4.1.22 Airport and Heliport MLS (Azimuth, Elevation and Back Azimuth) Records (PL)

  // 4.1.22.1 AIRPORT & HELIPORT MLS (PL)
  pl: {
    title: "Airport and Heliport MLS (PL)",
    re: ".{4}p.{7}l.{119}",
    // re: "....p.......l.......................................................................................................................",
    contNr: [
      {
        title: "4.1.22.1 Airport and Heliport MLS Primary Records",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Blank (Spacing (1) ", reference: " ", },
          { column: "7 thru 10 ", name: "Airport Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "14 thru 17 ", name: "MLS Identifier (4) ", reference: "5.44 ", },
          { column: "18 ", name: "MLS Category (1) ", reference: "5.80 ", },
          { column: "19 thru 21 ", name: "Blank (Spacing) (3) ", reference: " ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 thru 25 ", name: "Channel (3) ", reference: "5.166 ", },
          { column: "26 thru 27 ", name: "Blank (Spacing) (2) ", reference: " ", },
          { column: "28 thru 32 ", name: "Runway Identifier (5) ", reference: "5.46 ", },
          { column: "33 thru 41 ", name: "Azimuth Latitude (9) ", reference: "5.36 ", },
          { column: "42 thru 51 ", name: "Azimuth Longitude (10) ", reference: "5.37 ", },
          { column: "52 thru 55 ", name: "Azimuth Bearing (4) ", reference: "5.167 ", },
          { column: "56 thru 64 ", name: "Elevation Latitude (9) ", reference: "5.36 ", },
          { column: "65 thru 74 ", name: "Elevation Longitude (10) ", reference: "5.37 ", },
          { column: "75 thru 78 ", name: "Azimuth Position (4) ", reference: "5.48 ", },
          { column: "79 ", name: "Azimuth Position Reference (1) ", reference: "5.49 ", },
          { column: "80 thru 83 ", name: "Elevation Position (4) ", reference: "5.50 ", },
          { column: "84 thru 86 ", name: "Azimuth Proportional Angle Right (3) ", reference: "5.168 ", },
          { column: "87 thru 89 ", name: "Azimuth Proportional Angle Left (3) ", reference: "5.168 ", },
          { column: "90 thru 92 ", name: "Azimuth Coverage Right (3) ", reference: "5.172 ", },
          { column: "93 thru 95 ", name: "Azimuth Coverage Left (3) ", reference: "5.172 ", },
          { column: "96 thru 98 ", name: "Elevation Angle Span (3) ", reference: "5.169 ", },
          { column: "99 thru 103 ", name: "Magnetic Variation (5) ", reference: "5.39 ", },
          { column: "104 thru 108 ", name: "EL Elevation (5) ", reference: "5.74 ", },
          { column: "109 thru 112 ", name: "Nominal Elevation Angle (4) ", reference: "5.173 ", },
          { column: "113 thru 115 ", name: "Minimum Glide Path Angle (3) ", reference: "5.52 ", },
          { column: "116 thru 119 ", name: "Supporting Facility Identifier (4)  ", reference: "5.33  Note 1 ", },
          { column: "120 thru 121 ", name: "Supporting Facility ICAO Code (2) ", reference: "5.14  Note 1 ", },
          { column: "122 ", name: "Supporting Facility Section Code (1) ", reference: "5.4    Note 1 ", },
          { column: "123 ", name: "Supporting Facility Subsection Code (1) ", reference: "5.5    Note 1 ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
      {
        title: "4.1.22.2 Airport and Heliport MLS Continuation Records",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Blank (Spacing (1) ", reference: " ", },
          { column: "7 thru 10 ", name: "Airport Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "14 thru 17 ", name: "MLS Identifier (4) ", reference: "5.44 ", },
          { column: "18 ", name: "MLS Category (1) ", reference: "5.80 ", },
          { column: "19 thru 21 ", name: "Blank (Spacing) (3) ", reference: " ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24 thru 27 ", name: "Blank (Spacing) (4)  ", reference: " ", },
          { column: "28 thru 32 ", name: "Facility Characteristics (5) ", reference: "5.93 ", },
          { column: "33 thru 41 ", name: "Back Azimuth Latitude (9) ", reference: "5.36 ", },
          { column: "42 thru 51 ", name: "Back Azimuth Longitude (10) ", reference: "5.37 ", },
          { column: "52 thru 55 ", name: "Back Azimuth Bearing (4) ", reference: "5.167 ", },
          { column: "56 thru 64 ", name: "MLS Datum Point Latitude (9) ", reference: "5.36 ", },
          { column: "65 thru 74 ", name: "MLS Datum Point Longitude (10) ", reference: "5.37 ", },
          { column: "75 thru 78 ", name: "Back Azimuth Position (4) ", reference: "5.48 ", },
          { column: "79 ", name: "Back Azimuth Position Reference (1) ", reference: "5.49 ", },
          { column: "80 thru 83 ", name: "Blank (Spacing) (4)  ", reference: " ", },
          { column: "84 thru 86 ", name: "Back Azimuth Proportional Sector Right (3) ", reference: "5.168 ", },
          { column: "87 thru 89 ", name: "Back Azimuth Proportional Sector Left (3) ", reference: "5.168 ", },
          { column: "90 thru 92 ", name: "Back Azimuth Coverage Right (3) ", reference: "5.172 ", },
          { column: "93 thru 95 ", name: "Back Azimuth Coverage Left (3) ", reference: "5.172 ", },
          { column: "96 thru 100 ", name: "Back Azimuth True Bearing (5) ", reference: "5.94 ", },
          { column: "101 ", name: "Back Azimuth Bearing Source (1) ", reference: "5.95 ", },
          { column: "102 thru 106 ", name: "Azimuth True Bearing (5) ", reference: "5.94 ", },
          { column: "107 ", name: "Azimuth Bearing Source (1) ", reference: "5.95 ", },
          { column: "108 thru 110 ", name: "Glide Path Height at Landing Threshold (3) ", reference: "5.67 ", },
          { column: "111 thru 123 ", name: "Reserved (Expansion) (13)  ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
    ],
  },

  // 4.1.29.1 GLS (PT)
  pt: {
    title: "GLS (PT)",
    re: ".{4}p.{7}t.{119}",
    contNr: [
      {
        title: "4.1.29.1 GLS Primary Records",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Blank (1) ", reference: " ", },
          { column: "7 thru 10 ", name: "Airport or Heliport Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13  ", name: "Subsection code (1) ", reference: "5.5 ", },
          { column: "14 thru 17 ", name: "GLS Ref Path Identifier (4) ", reference: "5.44 ", },
          { column: "18 ", name: "GLS Category (1) ", reference: "5.80 ", },
          { column: "19 thru 21 ", name: "Blank (3) ", reference: " ", },
          { column: "22 ", name: "Continuation Number (1) ", reference: "5.16 ", },
          { column: "23 thru 27 ", name: "GLS Channel (5) ", reference: "5.244 ", },
          { column: "28 thru 32 ", name: "Runway Identifier (5) ", reference: "5.46 ", },
          { column: "33 thru 51 ", name: "Blank (19) ", reference: " ", },
          { column: "52 thru 55 ", name: "GLS Approach Bearing  (4)  (Note 1) ", reference: "5.47 ", },
          { column: "56 thru 64 ", name: "Station Latitude (9) ", reference: "5.36 ", },
          { column: "65 thru 74 ", name: "Station Longitude (10) ", reference: "5.37 ", },
          { column: "75 thru 78 ", name: "GLS Station ident (4) ", reference: "5.243 ", },
          { column: "79 thru 83 ", name: "Blank (5) ", reference: " ", },
          { column: "84 thru 85 ", name: "Service Volume Radius (2) ", reference: "5.245 ", },
          { column: "86 thru 87 ", name: "TDMA Slots (2) ", reference: "5.246 ", },
          { column: "88 thru 90 ", name: "GLS Approach Slope (3) ", reference: "5.52 ", },
          { column: "91 thru 95 ", name: "Magnetic Variation (5) ", reference: "5.39 ", },
          { column: "96 thru 97 ", name: "Reserved (2) ", reference: " ", },
          { column: "98 thru 102 ", name: "Station Elevation (5) ", reference: "5.74 ", },
          { column: "103 thru 105 ", name: "Datum Code (3) ", reference: "5.197 ", },
          { column: "106 thru 108 ", name: "Station Type (3) ", reference: "5.247 ", },
          { column: "109 thru 110 ", name: "Blank (2) ", reference: " ", },
          { column: "111 thru 115 ", name: "Station Elevation WGS 84 (5) ", reference: "5.248 ", },
          { column: "116 thru 123 ", name: "Blank (8) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record Number (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
      {
        title: "4.1.29.2 GLS Continuation Records",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Blank (1) ", reference: " ", },
          { column: "7 thru 10 ", name: "Airport or Heliport Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13  ", name: "Subsection code (1) ", reference: "5.5 ", },
          { column: "14 thru 17 ", name: "GLS Ref Path Identifier (4) ", reference: "5.44 ", },
          { column: "18 ", name: "GLS Category (1) ", reference: "5.80 ", },
          { column: "19 thru 21 ", name: "Blank (3) ", reference: " ", },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "24 thru 123 ", name: "Reserved (Expansion) (100) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },

        ],
      },
    ],
  },

  // 4.2.2.1 HELICOPTER TERMINAL WAYPOINT (HC)
  hc: {
    title: "Heliport Terminal Waypoint (HC)",
    re: ".{4}h.{7}c.{119}",
    contNr: [
      {
        title: "4.2.2.1 Heliport Terminal Waypoint Primary Records",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "7 thru 10 ", name: "Heliport Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "14 thru 18 ", name: "Waypoint Identifier (5) ", reference: "5.13 ", },
          { column: "19 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "22 ", name: "Continuation Record Number (1) ", reference: "5.16 ", },
          { column: "23 thru 26 ", name: "Blank (Spacing) (4) ", reference: " ", },
          { column: "27 thru 29 ", name: "Waypoint Type (3) ", reference: "5.42 ", },
          { column: "30 thru 31 ", name: "Waypoint Usage (2) ", reference: "5.82 ", },
          { column: "32 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "33 thru 41 ", name: "Waypoint Latitude (9) ", reference: "5.36 ", },
          { column: "42 thru 51 ", name: "Waypoint Longitude (10) ", reference: "5.37 ", },
          { column: "52 thru 74 ", name: "Blank (Spacing) (23) ", reference: " ", },
          { column: "75 thru 79 ", name: "Dynamic Magnetic Variation (5) ", reference: "5.39 ", },
          { column: "80 thru 84 ", name: "Reserved (Expansion) (5) ", reference: " ", },
          { column: "85 thru 87 ", name: "Datum Code (3) ", reference: "5.197 ", },
          { column: "88 thru 95 ", name: "Reserved (Expansion) (8) ", reference: " ", },
          { column: "96 thru 98 ", name: "Name Format Indicator (3) ", reference: "5.196 ", },
          { column: "99 thru 123 ", name: "Waypoint Name/Description (25) ", reference: "5.43 ", },
          { column: "124 thru 128 ", name: "File Record Number (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
      {
        title: "4.2.2.2 Heliport Terminal Waypoint Continuation Records",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "7 thru 10 ", name: "Heliport Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "14 thru 18 ", name: "Waypoint Identifier (5) ", reference: "5.13 ", },
          { column: "19 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "22 ", name: "Continuation Record Number (1) ", reference: "5.16 ", },
          { column: "23 ", name: "Application Type) (1) ", reference: "5.91 ", },
          { column: "24 thru 92 ", name: "Notes (69) ", reference: "5.61 ", },
          { column: "93 thru 123 ", name: "Reserved (Expansion) (31) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record Number (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
    ],
  },

  // 4.2.4.1 HELIPORT MINIMUM SECTOR ALTITUDE (MSA) (HS)
  hs: {
    title: "Heliport MSA (HS)",
    re: ".{4}h.{7}s.{119}",
    contNr: [
      {
        title: "4.1.5.1 Holding Pattern Primary",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "7 thru 10 ", name: "Heliport Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "14 thru 18 ", name: "MSA Center (5) ", reference: "5.144 ", },
          { column: "19 thru 20 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "21 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "22 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "23 ", name: "Multiple Code (1) ", reference: "5.130 ", },
          { column: "24 thru 38 ", name: "Reserved (Expansion) (15) ", reference: " ", },
          { column: "39  ", name: "Continuation Record Number (1) ", reference: "5.16 ", },
          { column: "40 thru 42 ", name: "Reserved (Spacing) (3)  ", reference: " ", },
          { column: "43 thru 48 ", name: "Sector Bearing (6) ", reference: "5.146 ", },
          { column: "49 thru 51 ", name: "Sector Altitude (3) ", reference: "5.147 ", },
          { column: "52 thru 53 ", name: "Sector Radius (2) ", reference: "5.145 ", },
          { column: "54 thru 59 ", name: "Sector Bearing (6) ", reference: "5.146 ", },
          { column: "60 thru 62 ", name: "Sector Altitude (3) ", reference: "5.147 ", },
          { column: "63 thru 64 ", name: "Sector Radius (2) ", reference: "5.145 ", },
          { column: "65 thru 70 ", name: "Sector Bearing (6) ", reference: "5.146 ", },
          { column: "71 thru 73 ", name: "Sector Altitude (3) ", reference: "5.147 ", },
          { column: "74 thru 75 ", name: "Sector Radius (2) ", reference: "5.145 ", },
          { column: "76 thru 81 ", name: "Sector Bearing (6) ", reference: "5.146 ", },
          { column: "82 thru 84 ", name: "Sector Altitude (3) ", reference: "5.147 ", },
          { column: "85 thru 86 ", name: "Sector Radius (2) ", reference: "5.145 ", },
          { column: "87 thru 92 ", name: "Sector Bearing (6) ", reference: "5.146 ", },
          { column: "93 thru 95 ", name: "Sector Altitude (3) ", reference: "5.147 ", },
          { column: "96 thru 97 ", name: "Sector Radius (2) ", reference: "5.145 ", },
          { column: "98 thru103 ", name: "Sector Bearing (6) ", reference: "5.146 ", },
          { column: "104 thru 106 ", name: "Sector Altitude (3) ", reference: "5.147 ", },
          { column: "107 thru 108 ", name: "Sector Radius (2) ", reference: "5.145 ", },
          { column: "109 thru 114 ", name: "Sector Bearing (6) ", reference: "5.146 ", },
          { column: "115 thru 117 ", name: "Sector Altitude (3) ", reference: "5.147 ", },
          { column: "118 thru119 ", name: "Sector Radius (2) ", reference: "5.145 ", },
          { column: "120 ", name: "Magnetic/True Indicator (1) ", reference: "5.165 ", },
          { column: "121 thru 123 ", name: "Reserved (Expansion) (3) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record Number (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },

        ],
      },
      {
        title: "4.2.4.2 Heliport MSA Primary Record Extension",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "7 thru 10 ", name: "Heliport Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "14 thru 18 ", name: "MSA Center (5) ", reference: "5.144 ", },
          { column: "19 thru 20 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "21 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "22 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "23 ", name: "Multiple Code (1) ", reference: "5.130 ", },
          { column: "24 thru 38 ", name: "Reserved (Expansion) (15) ", reference: " ", },
          { column: "39 ", name: "Continuation Record No. (1) ", reference: "5.16 ", },
          { column: "40 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "41 thru 42 ", name: "Reserved (Spacing) (2)  ", reference: " ", },
          { column: "43 thru 48  ", name: "Sector Bearing (6) ", reference: "5.146 ", },
          { column: "49 thru 51  ", name: "Sector Altitude (3) ", reference: "5.147 ", },
          { column: "52 thru 53  ", name: "Sector Radius (2) ", reference: "5.145 ", },
          { column: "54 thru 59  ", name: "Sector Bearing (6) ", reference: "5.146 ", },
          { column: "60 thru 62  ", name: "Sector Altitude (3) ", reference: "5.147 ", },
          { column: "63 thru 64  ", name: "Sector Radius (2) ", reference: "5.145 ", },
          { column: "65 thru 70  ", name: "Sector Bearing (6) ", reference: "5.146 ", },
          { column: "71 thru 73  ", name: "Sector Altitude (3) ", reference: "5.147 ", },
          { column: "74 thru 75  ", name: "Sector Radius (2) ", reference: "5.145 ", },
          { column: "76 thru 81  ", name: "Sector Bearing (6) ", reference: "5.146 ", },
          { column: "82 thru 84  ", name: "Sector Altitude (3) ", reference: "5.147 ", },
          { column: "85 thru 86  ", name: "Sector Radius (2) ", reference: "5.145 ", },
          { column: "87 thru 92  ", name: "Sector Bearing (6) ", reference: "5.146 ", },
          { column: "93 thru 95 ", name: "Sector Altitude (3) ", reference: "5.147 ", },
          { column: "96 thru 97 ", name: "Sector Radius (2) ", reference: "5.145 ", },
          { column: "98 thru 103 ", name: "Sector Bearing (6) ", reference: "5.146 ", },
          { column: "104 thru 106 ", name: "Sector Altitude (3) ", reference: "5.147 ", },
          { column: "107 thru 108 ", name: "Sector Radius (2) ", reference: "5.145 ", },
          { column: "109 thru 114 ", name: "Sector Bearing (6) ", reference: "5.146 ", },
          { column: "115 thru 117 ", name: "Sector Altitude (3) ", reference: "5.147 ", },
          { column: "118 thru 119 ", name: "Sector Radius (2) ", reference: "5.145 ", },
          { column: "120 ", name: "Magnetic/True Indicator (1) ", reference: "5.165 ", },
          { column: "121 thru 123 ", name: "Reserved (Expansion) (3) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
      {
        title: "4.2.4.3 Heliport MSA Continuation Records",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "6 ", name: "Blank (Spacing) (1) ", reference: " ", },
          { column: "7 thru 10 ", name: "Heliport Identifier (4) ", reference: "5.6 ", },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "13 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "14 thru 18 ", name: "MSA Center (5) ", reference: "5.144 ", },
          { column: "19 thru 20 ", name: "ICAO Code (2) ", reference: "5.14 ", },
          { column: "21 ", name: "Section Code (1) ", reference: "5.4 ", },
          { column: "22 ", name: "Subsection Code (1) ", reference: "5.5 ", },
          { column: "23 ", name: "Multiple Code (1) ", reference: "5.130 ", },
          { column: "24 thru 38 ", name: "Reserved (Expansion) (15) ", reference: " ", },
          { column: "39 ", name: "Continuation Record Number (1) ", reference: "5.16 ", },
          { column: "40 ", name: "Application Type (1) ", reference: "5.91 ", },
          { column: "41 thru 109 ", name: "Notes (69) ", reference: "5.61 ", },
          { column: "110 thru 123 ", name: "Reserved (Expansion) (14) ", reference: " ", },
          { column: "124 thru 128 ", name: "File Record Number (5) ", reference: "5.31 ", },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", },
        ],
      },
    ],
  },
};