export let arincLayout = {
  // xx: {
  //   title: "",
  //   re: ".{4}xx{128}",
  //   contNr: [
  //     {
  //       title: "4.1.5.1 Holding Pattern Primary",
  //       layout: [
  //         { name: "Record Type (1) ", reference: "5.2 ", textDirection: "" },
  //         { name: "Record Type (1) ", reference: "5.2 ", textDirection: "" },
  //       ],
  //     },
  //   ],
  // },

  dbpn: {
    title: "NDB NAVAID Record (DB or PN)",
    re: ".{4}(db|pn).{126}",
    contNr: [
      {
        title: "4.1.3.1 NDB NAVAID Primary",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", textDirection: "" },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", textDirection: "" },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", textDirection: "" },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", textDirection: "" },
          { column: "7 thru 10 ", name: "Airport ICAO Identifier (4) ", reference: "5.6 ", textDirection: "" },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", textDirection: "" },
          { column: "13 ", name: "Blank (Spacing) (1) ", reference: " ", textDirection: "" },
          { column: "14 thru 17 ", name: "NDB Identifier (4) ", reference: "5.33 ", textDirection: "" },
          { column: "18 thru 19 ", name: "Blank (Spacing) (2) ", reference: " ", textDirection: "" },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", textDirection: "" },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", textDirection: "" },
          { column: "23 thru 27 ", name: "NDB Frequency (5) ", reference: "5.34 ", textDirection: "" },
          { column: "28 thru 32 ", name: "NDB Class (5) ", reference: "5.35 ", textDirection: "" },
          { column: "33 thru 41 ", name: "NDB Latitude (9) ", reference: "5.36 ", textDirection: "" },
          { column: "42 thru 51 ", name: "NDB Longitude (10) ", reference: "5.37 ", textDirection: "" },
          { column: "52 thru 74 ", name: "Blank (Spacing) (23) ", reference: " ", textDirection: "" },
          { column: "75 thru 79 ", name: "Magnetic Variation (5) ", reference: "5.39 ", textDirection: "" },
          { column: "80 thru 85 ", name: "Blank (Spacing) (6) ", reference: " ", textDirection: "" },
          { column: "86 thru 90 ", name: "Reserved (Expansion) (5) ", reference: " ", textDirection: "" },
          { column: "91 thru 93 ", name: "Datum Code (3) ", reference: "5.197 ", textDirection: "" },
          { column: "94 thru 123 ", name: "NDB Name (30) ", reference: "5.71 ", textDirection: "" },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", textDirection: "" },
          { column: "129 thru 132 ", name: "Cycle Data (4) ", reference: "5.32 ", textDirection: "" },
        ],
      },
      {
        title: "4.1.3.2 NDB NAVAID Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", textDirection: "" },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", textDirection: "" },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", textDirection: "" },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", textDirection: "" },
          { column: "7 thru 10 ", name: "Airport ICAO Identifier (4) ", reference: "5.6 ", textDirection: "" },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", textDirection: "" },
          { column: "13 ", name: "Blank (Spacing) (1) ", reference: " ", textDirection: "" },
          { column: "14 thru 17 ", name: "NDB Identifier (4) ", reference: "5.33 ", textDirection: "" },
          { column: "18 thru 19 ", name: "Blank (Spacing) (2) ", reference: " ", textDirection: "" },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", textDirection: "" },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", textDirection: "" },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", textDirection: "" },
          { column: "24 thru 92 ", name: "Notes (69) ", reference: "5.61 ", textDirection: "" },
          { column: "93 thru 123 ", name: "Reserved (Expansion) (31) ", reference: " ", textDirection: "" },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", textDirection: "" },
          { column: "129 thru 132 ", name: "Cycle Data (4) ", reference: "5.32 ", textDirection: "" },
        ],
      }, {
        title: "4.1.3.3 NDB NAVAID Simulation Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", textDirection: "" },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", textDirection: "" },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", textDirection: "" },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", textDirection: "" },
          { column: "7 thru 10 ", name: "Airport ICAO Identifier (4) ", reference: "5.6 ", textDirection: "" },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", textDirection: "" },
          { column: "13 ", name: "Blank (Spacing) (1) ", reference: " ", textDirection: "" },
          { column: "14 thru 17 ", name: "NDB Identifier (4) ", reference: "5.33 ", textDirection: "" },
          { column: "18 thru 19 ", name: "Blank (Spacing) (2) ", reference: " ", textDirection: "" },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", textDirection: "" },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", textDirection: "" },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", textDirection: "" },
          { column: "24 thru 27 ", name: "Blank (Spacing) (4) ", reference: " ", textDirection: "" },
          { column: "28 thru 32 ", name: "Facility Characteristics (5) ", reference: "5.93 ", textDirection: "" },
          { column: "33 thru 79 ", name: "Reserved (Spacing) (47) ", reference: " ", textDirection: "" },
          { column: "80 thru 84 ", name: "Facility Elevation (5) ", reference: "5.92 ", textDirection: "" },
          { column: "85 thru 123 ", name: "Reserved (Expansion) (39) ", reference: " ", textDirection: "" },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", textDirection: "" },
          { column: "129 thru 132 ", name: "Cycle Data (4) ", reference: "5.32 ", textDirection: "" },
        ],
      }, {
        title: "4.1.3.4 NDB NAVAID Flight Planning Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", textDirection: "" },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", textDirection: "" },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", textDirection: "" },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", textDirection: "" },
          { column: "7 thru 10 ", name: "Airport ICAO Identifier (4) ", reference: "5.6 ", textDirection: "" },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14 ", textDirection: "" },
          { column: "13 ", name: "Blank (Spacing) (1) ", reference: " ", textDirection: "" },
          { column: "14 thru 17 ", name: "NDB Identifier (4) ", reference: "5.33 ", textDirection: "" },
          { column: "18 thru 19 ", name: "Blank (Spacing) (2) ", reference: " ", textDirection: "" },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", textDirection: "" },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", textDirection: "" },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", textDirection: "" },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", textDirection: "" },
          { column: "24 thru 27 ", name: "FIR Identifier (4) ", reference: "5.116 ", textDirection: "" },
          { column: "28 thru 31 ", name: "UIR Identifier (4) ", reference: "5.116 ", textDirection: "" },
          { column: "32 ", name: "Start/End Indicator (1) ", reference: "5.152 ", textDirection: "" },
          { column: "33 thru 43 ", name: "Blank (Spacing) (11) ", reference: " ", textDirection: "" },
          { column: "44 thru 123 ", name: "Reserved (Expansion) (80) ", reference: " ", textDirection: "" },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", textDirection: "" },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", textDirection: "" },
        ],
      },
    ],
  },

  eapc: {
    title: "Waypoint (EA) or (PC) ",
    re: ".{4}(ea|pc).{126}",
    contNr: [
      {
        title: "4.1.4.1 Waypoint Primary",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", textDirection: "" },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", textDirection: "" },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", textDirection: "" },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5", textDirection: "" },
          { column: "7 thru 10 ", name: "Region Code (4) ", reference: "5.41 ", textDirection: "" },
          { column: "11 thru 12 ", name: "ICAO Code (2)  ", reference: "5.14 ", textDirection: "" },
          { column: "13 ", name: "Subsection (1) ", reference: "5.5 ", textDirection: "" },
          { column: "14 thru 18 ", name: "Waypoint Identifier (5)  ", reference: "5.13 ", textDirection: "" },
          { column: "19 ", name: "Blank (Spacing) (1)  ", reference: " ", textDirection: "" },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", textDirection: "" },
          { column: "22 ", name: "Continuation Record No. (1)  ", reference: "5.16 ", textDirection: "" },
          { column: "23 thru 26 ", name: "Blank (Spacing) (4)  ", reference: " ", textDirection: "" },
          { column: "27 thru 29 ", name: "Waypoint Type (3) ", reference: "5.42 ", textDirection: "" },
          { column: "30 thru 31 ", name: "Waypoint Usage (2) ", reference: "5.82 ", textDirection: "" },
          { column: "32 ", name: "Blank (Spacing) (1)  ", reference: " ", textDirection: "" },
          { column: "33 thru 41 ", name: "Waypoint Latitude (9) ", reference: "5.36 ", textDirection: "" },
          { column: "42 thru 51 ", name: "Waypoint Longitude (10) ", reference: "5.37 ", textDirection: "" },
          { column: "52 thru 74 ", name: "Blank (Spacing) (23) ", reference: " ", textDirection: "" },
          { column: "75 thru 79 ", name: "Dynamic Magnetic Variation (5) ", reference: "5.39 ", textDirection: "" },
          { column: "80 thru 84 ", name: "Reserved (Expansion) (5) ", reference: " ", textDirection: "" },
          { column: "85 thru 87 ", name: "Datum Code (3) ", reference: "5.197 ", textDirection: "" },
          { column: "88 thru 95 ", name: "Reserved (Expansion) (8) ", reference: " ", textDirection: "" },
          { column: "96 thru 98 ", name: "Name Format Indicator (3) ", reference: "5.196 ", textDirection: "" },
          { column: "99 thru 123 ", name: "Waypoint Name/Description (25) ", reference: "5.43 ", textDirection: "" },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", textDirection: "" },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", textDirection: "" },
        ],
      },
      {
        title: "4.1.4.2 Waypoint Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", textDirection: "" },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", textDirection: "" },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", textDirection: "" },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5", textDirection: "" },
          { column: "7 thru 10 ", name: "Region Code (4) ", reference: "5.41 ", textDirection: "" },
          { column: "11 thru 12 ", name: "ICAO Code (2)  ", reference: "5.14 ", textDirection: "" },
          { column: "13 ", name: "Subsection (1) ", reference: "5.5 ", textDirection: "" },
          { column: "14 thru 18 ", name: "Waypoint Identifier (5)  ", reference: "5.13 ", textDirection: "" },
          { column: "19 ", name: "Blank (Spacing) (1)  ", reference: " ", textDirection: "" },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", textDirection: "" },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", textDirection: "" },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", textDirection: "" },
          { column: "24 thru 92 ", name: "Notes (69) ", reference: "5.61 ", textDirection: "" },
          { column: "93 thru 123 ", name: "Reserved (Expansion) (31) ", reference: " ", textDirection: "" },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", textDirection: "" },
          { column: "129 thru 132 ", name: "Cycle Data (4) ", reference: "5.32 ", textDirection: "" },
        ],
      }, {
        title: "4.1.4.3 Waypoint Flight Planning Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", textDirection: "" },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", textDirection: "" },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", textDirection: "" },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5", textDirection: "" },
          { column: "7 thru 10 ", name: "Region Code (4) ", reference: "5.41 ", textDirection: "" },
          { column: "11 thru 12 ", name: "ICAO Code (2)  ", reference: "5.14 ", textDirection: "" },
          { column: "13 ", name: "Subsection (1) ", reference: "5.5 ", textDirection: "" },
          { column: "14 thru 18 ", name: "Waypoint Identifier (5)  ", reference: "5.13 ", textDirection: "" },
          { column: "19 ", name: "Blank (Spacing) (1)  ", reference: " ", textDirection: "" },
          { column: "20 thru 21 ", name: "ICAO Code (2) ", reference: "5.14 ", textDirection: "" },
          { column: "22 ", name: "Continuation Record No. (1) ", reference: "5.16 ", textDirection: "" },
          { column: "23 ", name: "Application Type (1) ", reference: "5.91 ", textDirection: "" },
          { column: "24 thru 27 ", name: "FIR Identifier (4) ", reference: "5.116 ", textDirection: "" },
          { column: "28 thru 31 ", name: "UIR Identifier (4) ", reference: "5.116 ", textDirection: "" },
          { column: "32 ", name: "Start/End Indicator (1) ", reference: "5.152 ", textDirection: "" },
          { column: "33 thru 43 ", name: "Blank (Spacing) (11) ", reference: " ", textDirection: "" },
          { column: "44 thru 123 ", name: "Reserved (Expansion) (80) ", reference: " ", textDirection: "" },
          { column: "124 thru 128 ", name: "File Record No. (5)  ", reference: "5.31 ", textDirection: "" },
          { column: "129 thru 132 ", name: "Cycle Date (4)  ", reference: "5.32 ", textDirection: "" },
        ],
      },
    ],
  },

  ep: {
    title: "Holding Pattern (EP)",
    re: ".{4}ep.{126}",
    contNr: [
      {
        title: "4.1.5.1 Holding Pattern Primary",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", textDirection: "" },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", textDirection: "" },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", textDirection: "" },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", textDirection: "" },
          { column: "7 thru 10 ", name: "Region Code (4) ", reference: "5.41", textDirection: "" },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14", textDirection: "" },
          { column: "13 thru 27 ", name: "Blank (Spacing) (15) ", reference: " ", textDirection: "" },
          { column: "28 thru 29 ", name: "Duplicate Identifier (2) ", reference: "5.114 ", textDirection: "" },
          { column: "30 thru 34 ", name: "Fix Identifier (5) ", reference: "5.13 ", textDirection: "" },
          { column: "35 thru 36 ", name: "ICAO Code (2) ", reference: "5.14 ", textDirection: "" },
          { column: "37 ", name: "Section Code (1) ", reference: "5.4 ", textDirection: "" },
          { column: "38 ", name: "Subsection Code (1) ", reference: "5.5 ", textDirection: "" },
          { column: "39 ", name: "Continuation Record No. (1) ", reference: "5.16 ", textDirection: "" },
          { column: "40 thru 43 ", name: "Inbound Holding Course (4) ", reference: "5.62 ", textDirection: "" },
          { column: "44 ", name: "Turn Direction (1) ", reference: "5.63 ", textDirection: "" },
          { column: "45 thru 47 ", name: "Leg Length (3) ", reference: "5.64 ", textDirection: "" },
          { column: "48 thru 49 ", name: "Leg Time (2) ", reference: "5.65 ", textDirection: "" },
          { column: "50 thru 54 ", name: "Minimum Altitude (5) ", reference: "5.30 ", textDirection: "" },
          { column: "55 thru 59 ", name: "Maximum Altitude (5) ", reference: "5.127 ", textDirection: "" },
          { column: "60 thru 62 ", name: "Holding Speed (3) ", reference: "5.175 ", textDirection: "" },
          { column: "63 thru 65 ", name: "RNP (3) ", reference: "5.211 ", textDirection: "" },
          { column: "66 thru 71 ", name: "Arc Radius (6) ", reference: "5.204 ", textDirection: "" },
          { column: "72 thru 74 ", name: "Vertical Scale Factor (3) ", reference: "5.293 ", textDirection: "" },
          { column: "75 thru 77 ", name: "RVSM Minimum Level (3) ", reference: "5.294 ", textDirection: "" },
          { column: "78 thru 80 ", name: "RVSM Maximum Level (3) ", reference: "5.295 ", textDirection: "" },
          { column: "81 ", name: "Leg Inbound/Outbound Indicator (1) ", reference: "5.298 ", textDirection: "" },
          { column: "82 thru 98 ", name: "Reserved (Expansion) (17) ", reference: " ", textDirection: "" },
          { column: "99 thru 123 ", name: "Name (25) ", reference: "5.60 ", textDirection: "" },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", textDirection: "" },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", textDirection: "" },
        ],
      },
      {
        title: "4.1.5.2 Holding Pattern Continuation",
        layout: [
          { column: "1 ", name: "Record Type (1) ", reference: "5.2 ", textDirection: "" },
          { column: "2 thru 4 ", name: "Customer/Area Code (3) ", reference: "5.3 ", textDirection: "" },
          { column: "5 ", name: "Section Code (1) ", reference: "5.4 ", textDirection: "" },
          { column: "6 ", name: "Subsection Code (1) ", reference: "5.5 ", textDirection: "" },
          { column: "7 thru 10 ", name: "Region Code (4) ", reference: "5.41", textDirection: "" },
          { column: "11 thru 12 ", name: "ICAO Code (2) ", reference: "5.14", textDirection: "" },
          { column: "13 thru 27 ", name: "Blank (Spacing) (15) ", reference: " ", textDirection: "" },
          { column: "28 thru 29 ", name: "Duplicate Identifier (2) ", reference: "5.114 ", textDirection: "" },
          { column: "30 thru 34 ", name: "Fix Identifier (5) ", reference: "5.13 ", textDirection: "" },
          { column: "35 thru 36 ", name: "ICAO Code (2) ", reference: "5.14 ", textDirection: "" },
          { column: "37 ", name: "Section Code (1) ", reference: "5.4 ", textDirection: "" },
          { column: "38 ", name: "Subsection Code (1) ", reference: "5.5 ", textDirection: "" },
          { column: "39 ", name: "Continuation Record No. (1)  ", reference: "5.16 ", textDirection: "" },
          { column: "40 ", name: "Application Type (1) ", reference: "5.91 ", textDirection: "" },
          { column: "41 thru 109 ", name: "Notes (69) ", reference: "5.61 ", textDirection: "" },
          { column: "110 thru 123 ", name: "Reserved (Expansion) (14) ", reference: " ", textDirection: "" },
          { column: "124 thru 128 ", name: "File Record No. (5) ", reference: "5.31 ", textDirection: "" },
          { column: "129 thru 132 ", name: "Cycle Date (4) ", reference: "5.32 ", textDirection: "" },

        ],
      },
    ],
  },

};


// export let re = {
//   ep: "....ep..............................................................................................................................",
//   ea: "....ea..............................................................................................................................",
//   pc: "....pc..............................................................................................................................",
//   db: "....db..............................................................................................................................",
//   pn: "....pn.............................................................................................................................."
// };

// export let headerSelect = [
//   {value: "ep", title: "Holding pattern (EP)"},
//   {value: "ea", title: "Waypoint (EA)"},
//   {value: "pc", title: "Waypoint (PC)"},
//   {value: "db", title: "NDB navaid (DB)"},
//   {value: "pn", title: "NDB navaid (PN)"},
// ];